services:
  cache.factory.memcached:
    class: Vainyl\Memcached\Factory\MemcachedCacheFactory
    arguments: ['@connection.storage']
  connection.factory.memcached:
    class: Vainyl\Memcached\Factory\MemcachedConnectionFactory